version: '2'
services:

  mysqldb:
    image: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: cda
      MYSQL_DATABASE: cda
    ports:
        - 127.0.0.1:3306:3306
    volumes:
      - ./data:/data/db

  back:
    build: ./back_status
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      DB_USER: root
      DB_PASSWORD: cda
      DB_NAME: cda
      DB_HOST: mysqldb
      DB_PORT: 3306

  front:
    build: ./front_status
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - back