name: Lint and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [12, 14]

    steps:
    - uses: actions/checkout@v2

    # https://github.com/actions/setup-node
    - uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.nodejs }}

    - run: npm install
    # - run: npm test
    - run: npm lint